FROM node:20
WORKDIR /app
COPY package.json .
COPY *.js .
ENV MONGO="true" \
    MONGO_URL = "mongodb://mongodb:27017/catalogue"
# Environment=MONGO_URL="mongodb://<MONGODB-SERVER-IPADDRESS>:27017/catalogue", 
# here mongo is in same ec2 as catalogue and other so  container name owrks as DNS 
RUN npm install