FROM rabbitmq:3
ENV RABBITMQ_DEFAULT_USER=roboshop \
    RABBITMQ_DEFAULT_PASS=roboshop123


    
# 👉 RabbitMQ does two things automatically:
#     1. Creates user "roboshop"
#     2. Gives FULL permissions on default vhost (/)
# You automatically get:
#     User: roboshop
#     Vhost: /
#     Permissions:
#     configure → .*
#     write     → .*
#     read      →
